# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Favorite.destroy_all
Episode.destroy_all
User.destroy_all

Episode.create(season: 1, overall_episode: 1, season_episode: 1, title: "Mole Hunt", writer: "Adam Reed", air_date: Date.new(2009,9,17))
Episode.create(season: 1, overall_episode: 2, season_episode: 2, title: "Training Day", writer: "Adam Reed", air_date: Date.new(2010,1,14))
Episode.create(season: 1, overall_episode: 3, season_episode: 3, title: "Diversity Hire", writer: "Adam Reed", air_date: Date.new(2010,1,21))
Episode.create(season: 1, overall_episode: 4, season_episode: 4, title: "Killing Utne", writer: "Adam Reed", air_date: Date.new(2010,1,28))
Episode.create(season: 1, overall_episode: 5, season_episode: 5, title: "Honeypot", writer: "Adam Reed & Tony Carbone", air_date: Date.new(2010,2,4))
Episode.create(season: 1, overall_episode: 6, season_episode: 6, title: "Skorpio", writer: "Adam Reed", air_date: Date.new(2010,2,11))
Episode.create(season: 1, overall_episode: 7, season_episode: 7, title: "Skytanic", writer: "Adam Reed", air_date: Date.new(2010,2,18))
Episode.create(season: 1, overall_episode: 8, season_episode: 8, title: "The Rock", writer: "Adam Reed & Boswell Cocker", air_date: Date.new(2010,3,4))
Episode.create(season: 1, overall_episode: 9, season_episode: 9, title: "Job Offer", writer: "Adam Reed", air_date: Date.new(2010,3,11))
Episode.create(season: 1, overall_episode: 10, season_episode: 10, title: "Dial M for Mother", writer: "Adam Reed", air_date: Date.new(2010,3,18))
Episode.create(season: 2, overall_episode: 11, season_episode: 1, title: "Swiss Miss", writer: "Adam Reed", air_date: Date.new(2011,1,27))
Episode.create(season: 2, overall_episode: 12, season_episode: 2, title: "A Going Concern", writer: "Adam Reed", air_date: Date.new(2011,2,3))
Episode.create(season: 2, overall_episode: 13, season_episode: 3, title: "Blood Test", writer: "Adam Reed", air_date: Date.new(2011,2,10))
Episode.create(season: 2, overall_episode: 14, season_episode: 4, title: "Pipeline Fever", writer: "Adam Reed", air_date: Date.new(2011,2,17))
Episode.create(season: 2, overall_episode: 15, season_episode: 5, title: "The Double Deuce", writer: "Adam Reed", air_date: Date.new(2011,2,24))
Episode.create(season: 2, overall_episode: 16, season_episode: 6, title: "Tragical History", writer: "Adam Reed", air_date: Date.new(2011,3,3))
Episode.create(season: 2, overall_episode: 17, season_episode: 7, title: "Movie Star", writer: "Adam Reed", air_date: Date.new(2011,3,10))
Episode.create(season: 2, overall_episode: 18, season_episode: 8, title: "Stage Two", writer: "Adam Reed", air_date: Date.new(2011,3,17))
Episode.create(season: 2, overall_episode: 19, season_episode: 9, title: "Placebo Effect", writer: "Adam Reed", air_date: Date.new(2011,3,24))
Episode.create(season: 2, overall_episode: 20, season_episode: 10, title: "El Secuestro", writer: "Adam Reed", air_date: Date.new(2011,3,31))
Episode.create(season: 2, overall_episode: 21, season_episode: 11, title: "Jeu Monégasque", writer: "Adam Reed", air_date: Date.new(2011,4,7))
Episode.create(season: 2, overall_episode: 22, season_episode: 12, title: "White Nights", writer: "Adam Reed", air_date: Date.new(2011,4,14))
Episode.create(season: 2, overall_episode: 23, season_episode: 13, title: "Double Trouble", writer: "Adam Reed", air_date: Date.new(2011,4,21))
Episode.create(season: 3, overall_episode: 24, season_episode: 1, title: "Heart of Archness: Part I", writer: "Adam Reed", air_date: Date.new(2011,9,15))
Episode.create(season: 3, overall_episode: 25, season_episode: 2, title: "Heart of Archness: Part II", writer: "Adam Reed", air_date: Date.new(2011,9,22))
Episode.create(season: 3, overall_episode: 26, season_episode: 3, title: "Heart of Archness: Part III", writer: "Adam Reed", air_date: Date.new(2011,9,29))
Episode.create(season: 3, overall_episode: 27, season_episode: 4, title: "The Man from Jupiter", writer: "Adam Reed", air_date: Date.new(2012,1,19))
Episode.create(season: 3, overall_episode: 28, season_episode: 5, title: "El Contador", writer: "Tesha Kondrat & Adam Reed", air_date: Date.new(2012,1,26))
Episode.create(season: 3, overall_episode: 28, season_episode: 5, title: "El Contador", writer: "Tesha Kondrat & Adam Reed", air_date: Date.new(2012,1,26))
Episode.create(season: 3, overall_episode: 29, season_episode: 6, title: "The Limited", writer: "Adam Reed", air_date: Date.new(2012,2,2))
Episode.create(season: 3, overall_episode: 30, season_episode: 7, title: "Drift Problem", writer: "Adam Reed", air_date: Date.new(2012,2,9))
Episode.create(season: 3, overall_episode: 31, season_episode: 8, title: "Lo Scandalo", writer: "Adam Reed", air_date: Date.new(2012,2,16))
Episode.create(season: 3, overall_episode: 32, season_episode: 9, title: "Bloody Ferlin", writer: "Adam Reed", air_date: Date.new(2012,2,23))
Episode.create(season: 3, overall_episode: 33, season_episode: 10, title: "Crossing Over", writer: "Adam Reed", air_date: Date.new(2012,3,1))
Episode.create(season: 3, overall_episode: 34, season_episode: 11, title: "Skin Game", writer: "Chris Provenzano & Adam Reed", air_date: Date.new(2012,3,8))
Episode.create(season: 3, overall_episode: 35, season_episode: 12, title: "Space Race: Part I", writer: "Adam Reed", air_date: Date.new(2012,3,15))
Episode.create(season: 3, overall_episode: 36, season_episode: 13, title: "Space Race: Part II", writer: "Adam Reed", air_date: Date.new(2012,3,22))
Episode.create(season: 4, overall_episode: 37, season_episode: 1, title: "Fugue and Riffs", writer: "Adam Reed", air_date: Date.new(2013,1,17))
Episode.create(season: 4, overall_episode: 38, season_episode: 2, title: "The Wind Cries Mary", writer: "Adam Reed & Chris Provenzano", air_date: Date.new(2013,1,24))
Episode.create(season: 4, overall_episode: 39, season_episode: 3, title: "Legs", writer: "Adam Reed", air_date: Date.new(2013,1,31))
Episode.create(season: 4, overall_episode: 40, season_episode: 4, title: "Midnight Ron", writer: "Adam Reed & Tesha Kondrat", air_date: Date.new(2013,2,7))
Episode.create(season: 4, overall_episode: 41, season_episode: 5, title: "Viscous Coupling", writer: "Adam Reed", air_date: Date.new(2013,2,14))
Episode.create(season: 4, overall_episode: 42, season_episode: 6, title: "Once Bitten", writer: "Adam Reed", air_date: Date.new(2013,2,21))
Episode.create(season: 4, overall_episode: 43, season_episode: 7, title: "Live and Let Dine", writer: "Adam Reed", air_date: Date.new(2013,2,28))
Episode.create(season: 4, overall_episode: 44, season_episode: 8, title: "Coyote Lovely", writer: "Adam Reed", air_date: Date.new(2013,3,7))
Episode.create(season: 4, overall_episode: 45, season_episode: 9, title: "The Honeymooners", writer: "Mike Arnold & Adam Reed", air_date: Date.new(2013,3,14))
Episode.create(season: 4, overall_episode: 46, season_episode: 10, title: "Un Chien Tangerine", writer: "Adam Reed & Mike Arnold", air_date: Date.new(2013,3,21))
Episode.create(season: 4, overall_episode: 47, season_episode: 11, title: "The Papal Chase", writer: "Eric Sims & Adam Reed", air_date: Date.new(2013,3,28))
Episode.create(season: 4, overall_episode: 48, season_episode: 12, title: "Sea Tunt: Part I", writer: "Adam Reed", air_date: Date.new(2013,4,4))
Episode.create(season: 4, overall_episode: 49, season_episode: 13, title: "Sea Tunt: Part II", writer: "Adam Reed & Rick Cleveland", air_date: Date.new(2013,4,11))
Episode.create(season: 5, overall_episode: 50, season_episode: 1, title: "White Elephant", writer: "Adam Reed", air_date: Date.new(2014,1,13))
Episode.create(season: 5, overall_episode: 51, season_episode: 2, title: "A Kiss While Dying", writer: "Adam Reed", air_date: Date.new(2014,1,20))
Episode.create(season: 5, overall_episode: 52, season_episode: 3, title: "A Debt of Honor", writer: "Adam Reed", air_date: Date.new(2014,1,27))
Episode.create(season: 5, overall_episode: 53, season_episode: 4, title: "House Call", writer: "Adam Reed", air_date: Date.new(2014,2,3))
Episode.create(season: 5, overall_episode: 54, season_episode: 5, title: "Southbound and Down", writer: "Adam Reed & Ben Hoffman", air_date: Date.new(2014,2,24))
Episode.create(season: 5, overall_episode: 55, season_episode: 6, title: "Baby Shower", writer: "Adam Reed", air_date: Date.new(2014,3,3))
Episode.create(season: 5, overall_episode: 56, season_episode: 7, title: "Smugglers' Blues", writer: "Adam Reed", air_date: Date.new(2014,3,10))
Episode.create(season: 5, overall_episode: 57, season_episode: 8, title: "The Rules of Extraction", writer: "Adam Reed", air_date: Date.new(2014,3,17))
Episode.create(season: 5, overall_episode: 58, season_episode: 9, title: "On the Carpet", writer: "Adam Reed", air_date: Date.new(2014,3,24))
Episode.create(season: 5, overall_episode: 59, season_episode: 10, title: "Palace Intrigue: Part I", writer: "Adam Reed", air_date: Date.new(2014,3,31))
Episode.create(season: 5, overall_episode: 60, season_episode: 11, title: "Palace Intrigue: Part II", writer: "Adam Reed", air_date: Date.new(2014,4,7))
Episode.create(season: 5, overall_episode: 61, season_episode: 12, title: "Filibuster", writer: "Adam Reed", air_date: Date.new(2014,4,14))
Episode.create(season: 5, overall_episode: 62, season_episode: 13, title: "Arrival/Departure", writer: "Adam Reed", air_date: Date.new(2014,4,21))
Episode.create(season: 6, overall_episode: 63, season_episode: 1, title: "The Holdout", writer: "Adam Reed", air_date: Date.new(2015,1,8))
Episode.create(season: 6, overall_episode: 64, season_episode: 2, title: "Three to Tango", writer: "Adam Reed", air_date: Date.new(2015,1,15))
Episode.create(season: 6, overall_episode: 65, season_episode: 3, title: "The Archer Sanction", writer: "Adam Reed", air_date: Date.new(2015,1,22))
Episode.create(season: 6, overall_episode: 66, season_episode: 4, title: "Edie's Wedding", writer: "Adam Reed", air_date: Date.new(2015,1,29))
Episode.create(season: 6, overall_episode: 67, season_episode: 5, title: "Vision Quest", writer: "Adam Reed & Ben Hoffman", air_date: Date.new(2015,2,5))
Episode.create(season: 6, overall_episode: 68, season_episode: 6, title: "Sitting", writer: "Adam Reed", air_date: Date.new(2015,2,12))
Episode.create(season: 6, overall_episode: 69, season_episode: 7, title: "Nellis", writer: "Adam Reed", air_date: Date.new(2015,2,19))
Episode.create(season: 6, overall_episode: 70, season_episode: 8, title: "The Kanes", writer: "Adam Reed", air_date: Date.new(2015,2,26))
Episode.create(season: 6, overall_episode: 71, season_episode: 9, title: "Pocket Listing", writer: "Adam Reed", air_date: Date.new(2015,3,5))
Episode.create(season: 6, overall_episode: 72, season_episode: 10, title: "Reignition Sequence", writer: "Adam Reed", air_date: Date.new(2015,3,12))
Episode.create(season: 6, overall_episode: 73, season_episode: 11, title: "Achub Y Morfilod", writer: "Adam Reed & Mike Arnold", air_date: Date.new(2015,3,19))
Episode.create(season: 6, overall_episode: 74, season_episode: 12, title: "Drastic Voyage: Part I", writer: "Adam Reed & Casey Willis", air_date: Date.new(2015,3,26))
Episode.create(season: 6, overall_episode: 75, season_episode: 13, title: "Drastic Voyage: Part II", writer: "Adam Reed & Casey Willis", air_date: Date.new(2015,4,2))
Episode.create(season: 7, overall_episode: 76, season_episode: 1, title: "The Figgis Agency", writer: "Adam Reed", air_date: Date.new(2016,3,31))
Episode.create(season: 7, overall_episode: 77, season_episode: 2, title: "The Handoff", writer: "Adam Reed", air_date: Date.new(2016,4,7))
Episode.create(season: 7, overall_episode: 78, season_episode: 3, title: "Deadly Prep", writer: "Adam Reed", air_date: Date.new(2016,4,14))
Episode.create(season: 7, overall_episode: 79, season_episode: 4, title: "Motherless Child", writer: "Adam Reed", air_date: Date.new(2016,4,21))
Episode.create(season: 7, overall_episode: 80, season_episode: 5, title: "Bel Panto: Part I", writer: "Adam Reed", air_date: Date.new(2016,4,28))
Episode.create(season: 7, overall_episode: 81, season_episode: 6, title: "Bel Panto: Part II", writer: "Adam Reed", air_date: Date.new(2016,5,5))
Episode.create(season: 7, overall_episode: 82, season_episode: 7, title: "Double Indecency", writer: "Adam Reed", air_date: Date.new(2016,5,12))
Episode.create(season: 7, overall_episode: 83, season_episode: 8, title: "Liquid Lunch", writer: "Adam Reed", air_date: Date.new(2016,5,19))
Episode.create(season: 7, overall_episode: 84, season_episode: 9, title: "Deadly Velvet: Part I", writer: "Adam Reed", air_date: Date.new(2016,5,26))
Episode.create(season: 7, overall_episode: 85, season_episode: 10, title: "Deadly Velvet: Part II", writer: "Adam Reed", air_date: Date.new(2016,6,2))
Episode.create(season: 8, overall_episode: 86, season_episode: 1, title: "No Good Deed", writer: "Adam Reed", air_date: Date.new(2017,4,5))
Episode.create(season: 8, overall_episode: 87, season_episode: 2, title: "Berenice", writer: "Adam Reed", air_date: Date.new(2017,4,12))
Episode.create(season: 8, overall_episode: 88, season_episode: 3, title: "Jane Doe", writer: "Adam Reed", air_date: Date.new(2017,4,19))
Episode.create(season: 8, overall_episode: 89, season_episode: 4, title: "Ladyfingers", writer: "Adam Reed", air_date: Date.new(2017,4,26))
Episode.create(season: 8, overall_episode: 90, season_episode: 5, title: "Sleepers Wake", writer: "Adam Reed", air_date: Date.new(2017,5,3))
Episode.create(season: 8, overall_episode: 91, season_episode: 6, title: "Waxing Gibbous", writer: "Adam Reed", air_date: Date.new(2017,5,10))
Episode.create(season: 8, overall_episode: 92, season_episode: 7, title: "Gramercy, Halberd!", writer: "Adam Reed", air_date: Date.new(2017,5,17))
Episode.create(season: 8, overall_episode: 93, season_episode: 8, title: "Auflösung", writer: "Adam Reed", air_date: Date.new(2017,5,24))
Episode.create(season: 9, overall_episode: 94, season_episode: 1, title: "Strange Pilot", writer: "Adam Reed", air_date: Date.new(2018,4,25))
Episode.create(season: 9, overall_episode: 95, season_episode: 2, title: "Disheartening Situation", writer: "Adam Reed", air_date: Date.new(2018,5,2))
Episode.create(season: 9, overall_episode: 96, season_episode: 3, title: "Different Modes of Preparing the Fruit", writer: "Adam Reed", air_date: Date.new(2018,5,9))
Episode.create(season: 9, overall_episode: 97, season_episode: 4, title: "A Warrior in Costume", writer: "Adam Reed", air_date: Date.new(2018,5,16))
Episode.create(season: 9, overall_episode: 98, season_episode: 5, title: "Strange Doings in the Taboo Groves", writer: "Adam Reed & Mike Arnold", air_date: Date.new(2018,5,23))
Episode.create(season: 9, overall_episode: 99, season_episode: 6, title: "Some Remarks on Cannibalism", writer: "Adam Reed", air_date: Date.new(2018,5,30))
Episode.create(season: 9, overall_episode: 100, season_episode: 7, title: "Comparative Wickedness of Civilized and Unenlightened Peoples", writer: "Adam Reed", air_date: Date.new(2018,6,6))
Episode.create(season: 9, overall_episode: 101, season_episode: 8, title: "A Discovery", writer: "Adam Reed", air_date: Date.new(2018,6,13))
Episode.create(season: 10, overall_episode: 102, season_episode: 1, title: "Bort the Garj", writer: "Adam Reed", air_date: Date.new(2019,5,29))
Episode.create(season: 10, overall_episode: 103, season_episode: 2, title: "Happy Borthday", writer: "Adam Reed", air_date: Date.new(2019,6,5))
Episode.create(season: 10, overall_episode: 104, season_episode: 3, title: "The Leftovers", writer: "Mark Ganek", air_date: Date.new(2019,6,12))
Episode.create(season: 10, overall_episode: 105, season_episode: 4, title: "Dining with the Zarglorp", writer: "Shane Kosakowski", air_date: Date.new(2019,6,19))
Episode.create(season: 10, overall_episode: 106, season_episode: 5, title: "Mr. Deadly Goes to Town", writer: "Mark Ganek", air_date: Date.new(2019,6,26))
Episode.create(season: 10, overall_episode: 107, season_episode: 6, title: "Road Trip", writer: "Mike Arnold", air_date: Date.new(2019,7,10))
Episode.create(season: 10, overall_episode: 108, season_episode: 7, title: "Space Pirates", writer: "Kelly Galuska", air_date: Date.new(2019,7,17))
Episode.create(season: 10, overall_episode: 109, season_episode: 8, title: "Cubert", writer: "Adam Reed & Tesha Kondrat", air_date: Date.new(2019,7,24))
Episode.create(season: 10, overall_episode: 110, season_episode: 9, title: "Robert De Niro", writer: "Adam Reed", air_date: Date.new(2019,7,31))